# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# flooding.py
# Created on: 2018-04-19 10:24:19.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
floodzones_shp = "C:\\EsriPress\\Python\\Data\\Exercise02\\floodzones.shp"
basin_shp = "C:\\EsriPress\\Python\\Data\\Exercise02\\basin.shp"
flood_Clip_shp = "C:\\EsriPress\\Python\\Data\\Exercise02\\Results\\flood_Clip.shp"
flooding_shp = "C:\\EsriPress\\Python\\Data\\Exercise02\\Results\\flooding.shp"

# Process: Clip
arcpy.Clip_analysis(floodzones_shp, basin_shp, flood_Clip_shp, "")

# Process: Select
arcpy.Select_analysis(flood_Clip_shp, flooding_shp, "\"SFHA\"='IN'")

