# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# soil.py
# Created on: 2018-04-19 10:56:30.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
soils_shp = "C:\\EsriPress\\Python\\Data\\Exercise02\\soils.shp"
basin_shp = "C:\\EsriPress\\Python\\Data\\Exercise02\\basin.shp"
soils_Clip_shp = "C:\\EsriPress\\Python\\Data\\Exercise02\\Results\\soils_Clip.shp"
soils_Clip_Select_shp = "C:\\EsriPress\\Python\\Data\\Exercise02\\Results\\soils_Clip_Select.shp"

# Process: Clip
arcpy.Clip_analysis(soils_shp, basin_shp, soils_Clip_shp, "")

# Process: Select
arcpy.Select_analysis(soils_Clip_shp, soils_Clip_Select_shp, "\"FARMLNDCL\" ='Not prime farmland'")

